<a href="https://colab.research.google.com/github/cokerjesutayo/machine_learning_assignment/blob/main/Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

WEEK 3 ASSIGNMENT

## Section 1: Libraries

Question 1. A library is code written by others that you reuse to make your work easier and faster.

Question 2.
 NumPy -It is used for working with numbers and for fast mathematical calculations, especially with arrays.


Pandas- It is used for handling and analyzing data, like working with tables, similar to Excel spreadsheets.

## Section 2:Numpy

In [ ]:
import numpy as np

my_list= [10,20,30,40,50,60]

my_array= np.array(my_list)

print(my_array)

[10 20 30 40 50 60]

## Section 3: Pandas - Building and Exploring a Dataset

Step 1: Create your dataset

In [ ]:
import pandas as pd

In [ ]:
students={
    "StudentID": ["20010", "20020","20030","20040", "20050", "20060", "20070", "20080"],
    "Name":["Jesutayo","Ayomide", "Seun", "Ayotunde", "Ella","Ayomipo", "Tegiri","Daniel"],
    "Age":[21,34,56,78,21,45,79,50],
    "Department":["English", "Mathematics", "Biology", "Physics", "Art", "Commercial","Chemistry", "Building Tech"],
    "Score":[90,89,84,65,86,94,69,70],
    "Grade":["A","A","A","B","A","A","B","A"]
}
print(students)

{'StudentID': ['20010', '20020', '20030', '20040', '20050', '20060', '20070', '20080'], 'Name': ['Jesutayo', 'Ayomide', 'Seun', 'Ayotunde', 'Ella', 'Ayomipo', 'Tegiri', 'Daniel'], 'Age': [21, 34, 56, 78, 21, 45, 79, 50], 'Department': ['English', 'Mathematics', 'Biology', 'Physics', 'Art', 'Commercial', 'Chemistry', 'Building Tech'], 'Score': [90, 89, 84, 65, 86, 94, 69, 70], 'Grade': ['A', 'A', 'A', 'B', 'A', 'A', 'B', 'A']}

In [ ]:
df= pd.DataFrame(students)
print(df)

  StudentID      Name  Age     Department  Score Grade
0     20010  Jesutayo   21        English     90     A
1     20020   Ayomide   34    Mathematics     89     A
2     20030      Seun   56        Biology     84     A
3     20040  Ayotunde   78        Physics     65     B
4     20050      Ella   21            Art     86     A
5     20060   Ayomipo   45     Commercial     94     A
6     20070    Tegiri   79      Chemistry     69     B
7     20080    Daniel   50  Building Tech     70     A

Step 2: Look at your data

In [ ]:
# display the first 5 rows
df.head()

  StudentID      Name  Age   Department  Score Grade
0     20010  Jesutayo   21      English     90     A
1     20020   Ayomide   34  Mathematics     89     A
2     20030      Seun   56      Biology     84     A
3     20040  Ayotunde   78      Physics     65     B
4     20050      Ella   21          Art     86     A

In [ ]:
# display the last 3 rows
df.tail(3)

  StudentID     Name  Age     Department  Score Grade
5     20060  Ayomipo   45     Commercial     94     A
6     20070   Tegiri   79      Chemistry     69     B
7     20080   Daniel   50  Building Tech     70     A

Step 3: Understand the size

In [ ]:
df.shape

(8, 6)

It has 8 Rows and 6 Columns in the Students Dataframe

Step 4 : Get a summary

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   8 non-null      object
 1   Name        8 non-null      object
 2   Age         8 non-null      int64
 3   Department  8 non-null      object
 4   Score       8 non-null      int64
 5   Grade       8 non-null      object
dtypes: int64(2), object(4)
memory usage: 516.0+ bytes

No columns have missing values.Every column shows 8 non-null which means all 8 rows in each column contain data.

Step 5: Find unique values

In [ ]:
df["Age"].unique()

array([21, 34, 56, 78, 45, 79, 50])

In [ ]:
df["Grade"].unique()

array(['A', 'B'], dtype=object)

nunique()

In [ ]:
df["Age"].nunique()

7

In [ ]:
df["Grade"].nunique()

2

Step 6 : Reflect

I noticed that .unique() displays only the distinct values without repeating any, while .nunique() counts how many of those unique values are present.